{
 "title": "Sonarqube - Scan Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project_key", "label": "Project key", "query": { "query": "bugs" } }
  ]
 },
 "panels": [
  { "title": "Quality gates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quality Gate Status",
   "type": "stat",
   "description": "The state of the quality gate associated with your project. Possible values are ERROR and OK",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alert_status{alert_status=\"OK\",domain=\"Releasability\",project_key=\"bac\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Line of Code",
   "type": "stat",
   "description": "- Lines (lines): The number of physical lines \n- Lines of code (ncloc): The number of physical lines that contain at least one character\n- Comment lines (comment_lines): The number of lines containing comment",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comment_lines{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "lines{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ncloc{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The comment lines density",
   "type": "gauge",
   "description": "The comment lines density = comment lines / (lines of code + comment lines) * 100",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comment_lines_density{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of classes ",
   "type": "timeseries",
   "description": "The number of classes (including nested classes, interfaces, enums, and annotations).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "classes{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of statements",
   "type": "stat",
   "description": "The number of statements.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statements{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of functions",
   "type": "stat",
   "description": "The number of functions. Depending on the language, a function is defined as either a function, a method, or a paragraph.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "functions{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of files",
   "type": "stat",
   "description": "The number of files.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "files{domain=\"Size\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total of Issues",
   "type": "stat",
   "description": "The total count of issues in all states.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "violations{domain=\"Issues\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Violations",
   "type": "piechart",
   "description": "The total count of issues of the specified severity, where xxx is one of: blocker, critical, major, minor, info.",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocker_violations{domain=\"Issues\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "critical_violations{domain=\"Issues\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "info_violations{domain=\"Issues\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "major_violations{domain=\"Issues\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "minor_violations{domain=\"Issues\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "piechart",
   "description": "The total count of issues in the state.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_issues{domain=\"Issues\",project_key=\"$project_key\"} ",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "reopened_issues{domain=\"Issues\",project_key=\"$project_key\"} ",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "confirmed_issues{domain=\"Issues\",project_key=\"$project_key\"} ",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "false_positive_issues{domain=\"Issues\",project_key=\"$project_key\"} ",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "wont_fix_issues{domain=\"Issues\",project_key=\"$project_key\"} ",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "The number of vulnerability issues.",
   "type": "stat",
   "description": "The number of vulnerability issues.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vulnerabilities{domain=\"Security\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The effort to fix all vulnerability issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_remediation_effort{domain=\"Security\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of Security Hotspots",
   "type": "stat",
   "description": "The number of Security Hotspots",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_hotspots_reviewed_status{domain=\"SecurityReview\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "description": "Security Rating (security_rating)\n- A = 0 Vulnerabilities\n- B = at least 1 Minor Vulnerability\n- C = at least 1 Major Vulnerability\n- D = at least 1 Critical Vulnerability\n- E = at least 1 Blocker Vulnerability",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_rating{domain=\"Security\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Security review rating",
   "type": "stat",
   "description": "The security review rating is a letter grade based on the percentage of Reviewed Security Hotspots.\n- A = >= 80%\n- B = >= 70% and <80%\n- C = >= 50% and <70%\n- D = >= 30% and <50%\n- E = < 30%",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_review_rating{domain=\"SecurityReview\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Duplications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Duplications",
   "type": "stat",
   "description": "- Duplicated blocks (duplicated_blocks): The number of duplicated blocks of lines.\n- Duplicated lines (duplicated_lines): The number of lines involved in duplications.\n- Duplicated files (duplicated_files): The number of files involved in duplications.",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicated_lines{domain=\"Duplications\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "duplicated_files{domain=\"Duplications\",project_key=\"$project_key\"} ",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "duplicated_blocks{domain=\"Duplications\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Duplicated Lines (%)",
   "type": "gauge",
   "description": "Duplicated lines (%) (duplicated_lines_density): duplicated_lines / (lines of code) * 100",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duplicated_lines_density{domain=\"Duplications\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Coverage",
   "type": "gauge",
   "description": "Coverage = (CT + CF + LC)/(2*B + EL)\nwhere:\n- CT = conditions that have been evaluated to 'true' at least once\n- CF = conditions that have been evaluated to 'false' at least once\n- LC = covered lines = linestocover - uncovered_lines\n- B = total number of conditions\n- EL = total number of executable lines (lines_to_cover)\n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coverage{domain=\"Coverage\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of lines that covered by unit test",
   "type": "stat",
   "description": "The number of lines of code that could be covered by unit tests (for example, blank lines or full comments lines are not considered as lines to cover).",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lines_to_cover{domain=\"Coverage\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of unit tests.",
   "type": "stat",
   "description": "The number of unit tests.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tests{domain=\"Coverage\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The frequencies of rule",
   "type": "bargauge",
   "description": "The number append of rule in scan result ",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stat_rule{project_key=\"$project_key\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "The total number of bug issues",
   "type": "stat",
   "description": "The total number of bug issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bugs{domain=\"Reliability\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "description": "- A = 0 Bugs\n- B = at least 1 Minor Bug\n- C = at least 1 Major Bug\n- D = at least 1 Critical Bug\n- E = at least 1 Blocker Bug",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reliability_rating{domain=\"Reliability\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The effort to fix all bug issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reliability_remediation_effort{domain=\"Reliability\",project_key=\"$project_key\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Maintainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "The total count of code smell issues",
   "type": "stat",
   "description": "The total count of code smell issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "code_smells{domain=\"Maintainability\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Maintainability Rating",
   "type": "gauge",
   "description": "Formerly the SQALE rating.) The rating given to your project related to the value of your technical debt ratio. The default maintainability rating grid is:\n\n- A=0-0.05, B=0.06-0.1, C=0.11-0.20, D=0.21-0.5, E=0.51-1",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqale_rating{domain=\"Maintainability\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "stat",
   "description": "A measure of effort to fix all code smells. The measure is stored in minutes in the database. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqale_index{domain=\"Maintainability\",project_key=\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Complexity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Complexity / File",
   "type": "stat",
   "description": "Complexity / File",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_complexity{domain=\"Complexity\",project_key=\"$project_key\"}",
     "legendFormat": "{{project_key}}"
    }
   ]
  },
  {
   "title": "Cognitive Complexity",
   "type": "stat",
   "description": "How hard it is to understand the code's control flow",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cognitive_complexity{domain=\"Complexity\",project_key=\"$project_key\"}",
     "legendFormat": "{{project_key}}"
    }
   ]
  },
  {
   "title": "Cyclomatic Complexity",
   "type": "stat",
   "description": "Complexity refers to cyclomatic complexity, a quantitative metric used to calculate the number of paths through the code.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "complexity{domain=\"Complexity\",project_key=\"$project_key\"}",
     "legendFormat": "{{project_key}}"
    }
   ]
  },
  {
   "title": "Project analyses events",
   "type": "table",
   "description": "Project analyses events",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "project_analyses_and_events_info{project_key=\"$project_key\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}