{
 "title": "Sonarqube - System Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health check info",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_check_info{health=\"GREEN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "# Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total of project by language",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "project_count_by_language", "legendFormat": "{{language}}" }
   ]
  },
  {
   "title": "Total line of code by language",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ncloc_count_by_language", "legendFormat": "{{language}}" }
   ]
  },
  {
   "title": "Total line of code",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_line_of_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total of Project",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_of_project", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total of User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_of_user", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total of Plugins",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_of_plugins", "legendFormat": "__auto" }
   ]
  },
  { "title": "# Web Database Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pool Max Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "web_pool_max_connection", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pool Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "targets": [
    { "expr": "web_pool_active_connection", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pool Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "targets": [
    { "expr": "web_pool_idle_connections", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "# Web JVM State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "web_jvm_threads", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Max (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "web_jvm_heap_max", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Init (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "web_jvm_heap_init", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Committed (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "web_jvm_heap_commited", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Free Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "web_jvm_free_memory", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "web_jvm_heap_used", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Non Heap Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "web_jvm_non_heap_used", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "# Compute Engine JVM State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Non Heap Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "compute_engine_jvm_non_heap_used",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "targets": [
    { "expr": "compute_engine_jvm_threads", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Free Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "compute_engine_jvm_free_memory", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "compute_engine_jvm_heap_used", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "# Compute Engine Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "In Progress Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "compute_engine_tasks_inprogress",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed With Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "compute_engine_tasks_error_progress",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "targets": [
    { "expr": "compute_engine_tasks_worker", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Processing Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "compute_engine_tasks_progressing_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed With Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "compute_engine_tasks_success_progress",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "targets": [
    { "expr": "compute_engine_tasks_pending", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "# Compute Engine Database Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "Pool Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "compute_engine_pool_idle_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool Max Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "compute_engine_pool_max_connection",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "compute_engine_pool_active_connection",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "# Server Push Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "SonarLint Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 73 },
   "targets": [
    { "expr": "sonarlint_client", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "# Search Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Index components - Docs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 79 },
   "targets": [
    { "expr": "index_docs", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "# Search State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 85 },
   "targets": [
    { "expr": "jvm_threads", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Store Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    { "expr": "store_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk Available",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "disk_available", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}